---
- name: Run facts gather test
  hosts: all
  become: true
  gather_facts: false
  vars_files:
    - group_vars/become.yml

  tasks:
    - name: Gather facts from remote hosts
      ansible.builtin.setup:
        gather_subset:
          - apparmor
          - architecture
          - default_ipv4
          - default_ipv6
          - devices
          - distribution
          - distribution_major_version
          - distribution_release
          - distribution_version
          - dns
          # - interfaces # enp0s31f6
          - env
          - selinux

    - name: Ensure local .ansible/facts_cache dir exists
      ansible.builtin.file:
        path: ./.ansible
        state: directory
        mode: "0755"
        owner: user
        group: user
      delegate_to: localhost

    - name: Save facts to local JSON file
      ansible.builtin.copy:
        content: "{{ ansible_facts | to_nice_json }}"
        dest: ./.ansible/facts.json
        mode: "0644"
        owner: user
        group: user
      delegate_to: localhost
