---
all:
  hosts:
    homeserver_main:
      ansible_host: 192.168.0.100
  vars:
    ansible_user: user
    ansible_ssh_private_key_file: ~/.ssh/personal.pub

homeserver:
  hosts:
    homeserver_main:
