---
all:
  hosts:
    homeserver:
      ansible_host: 192.168.0.100
    netserver:
      ansible_host: 192.168.0.99
  vars:
    ansible_user: user
    ansible_ssh_private_key_file: ~/.ssh/personal.pub
