---
- name: Run homeserver maintainance
  hosts: homeserver
  become: true
  gather_facts: false

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Upgrade packages
      ansible.builtin.apt:
        upgrade: dist

    - name: Prune containers, images, networks, volumes and builder_cache
      community.docker.docker_prune:
        containers: true
        containers_filters:
          until: 10m
        images: true
        images_filters:
          util: 168h
          dangling: true
        networks: true
        networks_filter:
          until: 10m
        volumes: true
        builder_cache: true
