---
- name: Run homelab playbook (all)
  hosts: all
  become: true
  gather_facts: false
  vars_files:
    - group_vars/all-secret.yml

  pre_tasks:
    - name: Gather minimal facts
      ansible.builtin.setup:
        gather_subset:
          - "!all"
      tags: [always]

    - name: Show available facts
      ansible.builtin.debug:
        var: ansible_facts
      when: false

  roles:
    - role: essential

- name: Run homelab playbook (homeserver)
  hosts: homeserver
  become: true
  gather_facts: false
  vars_files:
    - group_vars/all-secret.yml
    - group_vars/homeserver-secret.yml

  roles:
    - role: homeserver
    - role: services

- name: Run homelab playbook (netserver)
  hosts: netserver
  become: true
  gather_facts: false
  vars_files:
    - group_vars/all-secret.yml
    - group_vars/netserver-secret.yml

  roles:
    - role: netserver
    - role: services
