---
- name: Run homelab playbook (all)
  hosts: all
  become: true
  gather_facts: false
  vars_files:
    - group_vars/all/secret.yml

  pre_tasks:
    - name: Gather minimal facts
      ansible.builtin.setup:
        gather_subset:
          - "!all"
      tags: [always]

    - name: Show available facts
      ansible.builtin.debug:
        var: ansible_facts
      tags: [never, debug]

  tasks:
    - name: Run maintainance
      ansible.builtin.include_tasks: tasks/maintainance.yml
      tags: [never, maintainance, compose_maintain]

  roles:
    - role: common

- name: Run homelab playbook (homeserver)
  hosts: homeserver
  become: true
  gather_facts: false
  vars_files:
    - group_vars/all/secret.yml
    - host_vars/homeserver/secret.yml

  roles:
    - role: homeserver
    - role: config
    - role: container
